---
on:
  workflow_call:

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'automation-create-release') }}
    uses: uclahs-cds/tool-create-release/.github/workflows/wf-finalize-release.yaml@v1.1.0
    with:
      draft: false
    secrets: inherit
